// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  frontend: [
    {
      type: "autogenerated",
      dirName: "frontend",
    },
  ],
  backend: [
    {
      type: "autogenerated",
      dirName: "backend",
    },
  ],
  cs: [
    {
      type: "autogenerated",
      dirName: "CS",
    },
  ],
  infra: [
    {
      type: "autogenerated",
      dirName: "etc/infra",
    },
  ],
};

module.exports = sidebars;
